config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :students
  root 'home#index'
  
  namespace :admin do
    resources :courses do
      resources :lessons, only: %i[show new create edit update destroy]
    end

    resources :teachers
  end

  namespace :student do
    resources :courses, only: %i[index show] do
      resources :lessons, only: %i[show]
  
      post 'enroll', on: :member
      get 'my_enroll', on: :collection
    end
  end

  resources :courses, only: %i[index show]

  namespace :api do
    namespace :v1 do
      resources :courses, only: %i[index show create], param: :code
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :teacher
  has_many :lessons
  has_many :users, through: :enrollments
  has_many :students, through: :enrollments

  validates :name, :code, :price, presence: true
  validates :code, uniqueness: true

  scope :available, -> { where(enrollment_deadline: Date.current..) }
  scope :min_to_max, -> { order(price: :asc) }
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  validates :name, :content, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :enrollments
  has_many :courses, through: :enrollments
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :courses, dependent: :destroy

  validates :name, :email, presence: true
  validates :email, uniqueness: true

  has_one_attached :profile_picture

  before_create :attach_default_profile_picture

  def attach_default_profile_picture
    return if profile_picture.attached?

    profile_picture.attach(io: File.open('spec/fixtures/default.png'),
                           filename: 'default.png')
  end

  def display_name
    "#{name} - #{email}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
  before_action :authenticate_user!
  layout 'admin'
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::AdminController
  before_action :set_course, only: %i[show edit update destroy]

  def index
    @courses = Course.all
  end

  def show; end

  def new
    @teachers = Teacher.all
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to admin_course_path(@course)
    else
      @teachers = Teacher.all
      render :new
    end
  end

  def edit
    @teachers = Teacher.all
  end

  def update
    if @course.update(course_params)
      redirect_to admin_course_path(@course)
    else
      @teachers = Teacher.all
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to admin_courses_path
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :description, :code, :price, :teacher_id, :enrollment_deadline)
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::AdminController
  before_action :set_course, only: %i[show new create edit update destroy]
  before_action :set_lesson, only: %i[show edit update destroy]

  def show; end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = @course.lessons.build(lesson_params)

    if @lesson.save
      redirect_to admin_course_path(@course)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @lesson.update(lesson_params)
      redirect_to admin_course_path(@course)
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    redirect_to admin_course_path(@course)
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:name, :content)
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::AdminController
  before_action :set_teacher, only: %i[show edit update destroy]

  def index
    @teachers = Teacher.all
  end

  def show; end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to admin_teacher_path(@teacher)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @teacher.update(teacher_params)
      redirect_to admin_teacher_path(@teacher)
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to admin_teachers_path
  end

  private

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :email, :bio, :profile_picture)
  end
end

app/controllers/api/v1/courses_controller.rb
class Api::V1::CoursesController < ActionController::API
  def index
    @courses = Course.all
    render json: @courses.as_json(except: %i[id created_at updated_at teacher_id], include: :teacher)
  end

  def show
    @course = Course.find_by(code: params[:code])
    if @course
      render json: @course
    else
      head :not_found
    end
  end

  def create
    @course = Course.new(course_params)
    @course.save!
    render json: @course, status: :created
  rescue ActiveRecord::RecordInvalid
    render json: @course.errors, status: :unprocessable_entity
  rescue ActionController::ParameterMissing
    render json: { errors: 'Parâmetros inválidos' }, status: :precondition_failed
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :code, :price, :teacher_id, :enrollment_deadline)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show]

  def index
    @courses = Course.all
  end

  def show; end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :description, :code, :price, :teacher_id, :enrollment_deadline)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout :verify_layout

  def index
    @courses = Course.available.min_to_max
  end

  def verify_layout
    if user_signed_in?
      'admin'
    elsif student_signed_in?
      'student'
    else
      'application'
    end
  end
end

app/controllers/student/courses_controller.rb
class Student::CoursesController < Student::StudentController
  before_action :set_course, only: %i[show enroll]

  def index
    @courses = Course.all
  end

  def show; end

  def enroll
    current_student.enrollments.create!(course: @course, price: @course.price)
    redirect_to my_enroll_student_courses_path, notice: 'Curso comprado com sucesso'
  end

  def my_enroll
    @enrollments = current_student.enrollments
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :description, :code, :price, :teacher_id, :enrollment_deadline)
  end
end

app/controllers/student/lessons_controller.rb
class Student::LessonsController < Student::StudentController
  before_action :authenticate_student!, only: %i[show]
  before_action :set_course, only: %i[show]
  before_action :set_lesson, only: %i[show]
  before_action :user_has_enrollment, only: %i[show]

  def show; end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def user_has_enrollment
    redirect_to [:student, @lesson.course] unless current_student.courses.include?(@lesson.course)
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:name, :content)
  end
end

app/controllers/student/student_controller.rb
class Student::StudentController < ActionController::Base
  layout 'student'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/courses/_form.html.erb
<%= form_with model: [:admin, course] do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :description %>
    <%= form.text_area :description %>
    <%= form.label :code %>
    <%= form.text_field :code %>
    <%= form.label :price %>
    <%= form.text_field :price %>
    <%= form.label :enrollment_deadline %>
    <%= form.text_field :enrollment_deadline %>
    <%= form.label :teacher_id %>
    <%= form.collection_select :teacher_id, teachers, :id, :display_name %>
    <%= form.submit %>
<% end %>

<% course.errors.each do |error| %>
    <%= error.full_message %>
<% end %>

app/views/admin/courses/edit.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form', course: @course, teachers: @teachers %>

app/views/admin/courses/index.html.erb
<% if @courses.empty? %>
    <p><%= t 'messages.no_course' %></p>
<% end %>

<% @courses.each do |course| %>
    <h1><%= link_to course.name, admin_course_path(course) %></h1>
    <p><%= course.description %></p>
    <p><%= number_to_currency course.price %></p>
<% end %>

<%= link_to t('.register_course'), new_admin_course_path %>
<%= link_to t('helpers.button.back'), root_path %>

app/views/admin/courses/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form', course: @course, teachers: @teachers %>

app/views/admin/courses/show.html.erb
<h1><%= @course.name %></h1>
<dl>
    <dt><%= Course.human_attribute_name(:description) %></dt>
    <dd><%= @course.description %></dd>

    <dt><%= Course.human_attribute_name(:code) %></dt>
    <dd><%= @course.code %></dd>

    <dt><%= Course.human_attribute_name(:price) %></dt>
    <dd><%= number_to_currency @course.price %></dd>

    <dt><%= Course.human_attribute_name(:enrollment_deadline) %></dt>
    <dd><%= l @course.enrollment_deadline %></dd>

    <dt><%= Course.human_attribute_name(:teacher) %></dt>
    <dd><%= link_to @course.teacher.name, admin_teacher_path(@course.teacher) %></dd>
</dl>

<%= link_to t('.register_lesson'), new_admin_course_lesson_path(@course) %>

<% if @course.lessons.any? %>
    <% @course.lessons.each do |lesson|%>
        <%= link_to lesson.name, [:admin, @course, lesson] %>
    <% end %>
<% else %>
    <p><%= t('.no_available_lesson') %></p>
<% end %>

<%= link_to t('helpers.button.edit'), edit_admin_course_path(@course) %>
<%= link_to t('helpers.button.delete'), [:admin, @course], method: :delete %>
<%= link_to t('helpers.button.back'), admin_courses_path %>

app/views/admin/lessons/_form.html.erb
<%= form_with model: [:admin, course, lesson] do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :content %>
    <%= form.text_area :content %>
    <%= form.submit submit_text %>
<% end %>

<% if lesson.errors.any? %>
    <p>Foram encontrados <%= lesson.errors.count %> erro(s) </p>
    <ul>
        <% lesson.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </ul> 
<% end %>

app/views/admin/lessons/edit.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form', course: @course, lesson: @lesson, submit_text: 'Editar' %>

app/views/admin/lessons/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form', course: @course, lesson: @lesson, submit_text: 'Registrar aula' %>

app/views/admin/lessons/show.html.erb
<h1><%= @lesson.name %></h1>
<p><%= @lesson.content %></p>

<%= link_to t('.button_edit'), edit_admin_course_lesson_path(@course, @lesson) %>
<%= link_to t('.button_delete'), admin_course_lesson_path(@course, @lesson), method: :delete %>
<%= link_to t('.button_back'), admin_course_path(@course) %>

app/views/admin/teachers/_form.html.erb
<%= form_with model: [:admin, teacher] do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :email %>
    <%= form.text_field :email %>
    <%= form.label :bio %>
    <%= form.text_area :bio %>
    <%= form.label :profile_picture %>
    <%= form.file_field :profile_picture %>
    <%= form.submit %>
<% end %>

<% teacher.errors.each do |error| %>
    <%= error.full_message %>
<% end %>

app/views/admin/teachers/edit.html.erb
<h1><%= t('.title') %></h1>
<%= render 'form', teacher: @teacher %>

app/views/admin/teachers/index.html.erb
<% if @teachers.empty? %>
    <p><%= t('.no_teacher') %></p>
<% end %>

<% @teachers.each do |teacher| %>
    <%= link_to teacher.name, admin_teacher_path(teacher)  %>
    <%= teacher.email %>
    <%= teacher.bio %>
    <%= image_tag teacher.profile_picture %>
<% end %>

<%= link_to t('.register_teacher'), new_admin_teacher_path %>
<%= link_to t('.button_back'), root_path %>

app/views/admin/teachers/new.html.erb
<h1><%= t('.title') %></h1>
<%= render 'form', teacher: @teacher %>

app/views/admin/teachers/show.html.erb
<h1><%= @teacher.name %></h1>

<h2><%= Teacher.human_attribute_name(:email) %></h2>
<p><%= @teacher.email %></p>

<h2><%= Teacher.human_attribute_name(:bio) %></h2>
<p><%= @teacher.bio %></p>

<h2><%= Teacher.human_attribute_name(:profile_picture) %></h2>
<p><%= image_tag @teacher.profile_picture %></p>

<%= link_to t('.button_edit'), edit_admin_teacher_path(@teacher) %>
<%= link_to t('.button_delete'), [:admin, @teacher], method: :delete %>
<%= link_to t('.button_back'), admin_teachers_path %>

app/views/courses/index.html.erb
<% if @courses.empty? %>
    <p><%= t('.no_course') %></p>
<% end %>

<% @courses.each do |course| %>
    <h1><%= link_to course.name, course_path(course) %></h1>
    <p><%= course.description %></p>
    <p><%= number_to_currency course.price %></p>
<% end %>

<%= link_to t('.register_course'), new_course_path %>
<%= link_to t('.button_back'), root_path %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
<dl>
    <dt><%= Course.human_attribute_name(:description) %></dt>
    <dd><%= @course.description %></dd>

    <dt><%= Course.human_attribute_name(:code) %></dt>
    <dd><%= @course.code %></dd>

    <dt><%= Course.human_attribute_name(:price) %></dt>
    <dd><%= number_to_currency @course.price %></dd>

    <dt><%= Course.human_attribute_name(:enrollment_deadline) %></dt>
    <dd><%= l @course.enrollment_deadline %></dd>

    <dt><%= Course.human_attribute_name(:teacher) %></dt>
    <dd><%= @course.teacher.name %></dd>
</dl>

<% if student_signed_in? %>
    <% if current_student.courses.exclude?(@course) %>
        <% if @course.enrollment_deadline >= Date.current %>
            <%= link_to t('.buy'), enroll_student_course_path, method: :post %>
        <% else %>
            <p><%= t('.enrollment_over') %></p>
        <% end %>
    <% end %>
<% else %>
    <p><%= t('.login_message_html', login_href: (link_to 'login', new_student_session_path)) %></p>
<% end %>

<% if @course.lessons.any? %>
    <% @course.lessons.each do |lesson|%>
        <% if current_user && current_user.courses.include?(@course) %>
            <%= link_to lesson.name, course_lesson_path(@course, lesson) %>
        <% else %>
            <%= lesson.name %>
        <% end %>
    <% end %>
<% else %>
    <p><%= t('.no_available_lesson') %></p>
<% end %>

<%= link_to t('.button_back'), courses_path %>

app/views/home/index.html.erb
<div class="container mt-5">
    <div class="vh-100 align-items-center">
        <h1>Codeplay</h1>
        <h3>Boas vindas ao sistema de gestão de cursos e aulas</h3>
    </div>

    <% if @courses.any? %>
        <h3>Cursos disponíveis</h3>
        <% @courses.each do |course| %>
            <% if student_signed_in? %>
                <%= link_to course.name, student_course_path(course) %>
            <% else %>
                <%= link_to course.name, course_path(course) %>
            <% end %>
            <%= course.description %>
            <%= number_to_currency course.price %>
        <% end %>
    <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeplay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Cursos', admin_courses_path %>
      <%= link_to 'Professores', admin_teachers_path %>
      <% if user_signed_in? %>
        <%= current_user.email %>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Entrar', new_user_session_path %>
        <%= link_to 'Registrar-me', new_user_registration_path %>
      <% end %>
    </nav>

    <% if notice %>
      <div>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeplay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <h1 class="navbar-brand ms-2">
          <a class="navbar-brand" href=<%= root_path %>>Codeplay</a>
        </h1>
        <ul class="navbar-nav justify-content-end">
          <% if user_signed_in? %>
            <li class="nav-item"><%= current_user.email %></li>
            <li class="nav-item"><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class="nav-item"><a class="nav-link" href=<%= new_user_session_path %>>Entrar</a></li>
            <li class="nav-item"><a class="nav-link" href=<%= new_user_registration_path %>>Registrar-me</a></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/student.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeplay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Cursos', student_courses_path %>
      <%= link_to 'Professores', admin_teachers_path %>
      <% if student_signed_in? %>
        <%= current_student.email %>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Entrar', new_user_session_path %>
        <%= link_to 'Registrar-me', new_user_registration_path %>
      <% end %>
    </nav>

    <% if notice %>
      <div>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with model: [course, lesson] do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :content %>
    <%= form.text_area :content %>
    <%= form.submit submit_text %>
<% end %>

<% if lesson.errors.any? %>
    <p>Foram encontrados <%= lesson.errors.count %> erro(s) </p>
    <ul>
        <% lesson.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </ul> 
<% end %>

app/views/lessons/edit.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form', course: @course, lesson: @lesson, submit_text: 'Editar' %>

app/views/lessons/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form', course: @course, lesson: @lesson, submit_text: 'Registrar aula' %>

app/views/lessons/show.html.erb
<h1><%= @lesson.name %></h1>
<p><%= @lesson.content %></p>

<%= link_to t('.button_edit'), edit_course_lesson_path(@lesson) %>
<%= link_to t('.button_delete'), course_lesson_path(@course, @lesson), method: :delete %>
<%= link_to t('.button_back'), course_path(@course) %>

app/views/student/courses/index.html.erb
<% if @courses.empty? %>
    <p><%= t('.no_course') %></p>
<% end %>

<% @courses.each do |course| %>
    <h1><%= link_to course.name, student_course_path(course) %></h1>
    <p><%= course.description %></p>
    <p><%= number_to_currency course.price %></p>
<% end %>

<%= link_to t('.button_back'), root_path %>

app/views/student/courses/my_enroll.html.erb
<h1>Meus cursos</h1>

<% @enrollments.each do |enrollment| %>
    <p><%= enrollment.course.name %></p>
    <p>Comprado em <%= enrollment.created_at %> por <%= number_to_currency enrollment.price %> </p>
<% end %>

app/views/student/courses/show.html.erb
<h1><%= @course.name %></h1>
<dl>
    <dt><%= Course.human_attribute_name(:description) %></dt>
    <dd><%= @course.description %></dd>

    <dt><%= Course.human_attribute_name(:code) %></dt>
    <dd><%= @course.code %></dd>

    <dt><%= Course.human_attribute_name(:price) %></dt>
    <dd><%= number_to_currency @course.price %></dd>

    <dt><%= Course.human_attribute_name(:enrollment_deadline) %></dt>
    <dd><%= l @course.enrollment_deadline %></dd>

    <dt><%= Course.human_attribute_name(:teacher) %></dt>
    <dd><%= @course.teacher.name %></dd>
</dl>

<% if student_signed_in? %>
    <% if current_student.courses.exclude?(@course) %>
        <% if @course.enrollment_deadline >= Date.current %>
            <%= link_to t('.buy'), enroll_student_course_path, method: :post %>
        <% else %>
            <p><%= t('.enrollment_over') %></p>
        <% end %>
    <% end %>
<% else %>
    <p><%= t('.login_message_html', login_href: (link_to 'login', new_student_session_path)) %></p>
<% end %>

<% if @course.lessons.any? %>
    <% @course.lessons.each do |lesson|%>
        <% if current_student && current_student.courses.include?(@course) %>
            <%= link_to lesson.name, student_course_lesson_path(@course, lesson) %>
        <% else %>
            <%= lesson.name %>
        <% end %>
    <% end %>
<% else %>
    <p><%= t('.no_available_lesson') %></p>
<% end %>

<%= link_to t('.button_back'), student_courses_path %>

app/views/student/lessons/show.html.erb
<h1><%= @lesson.name %></h1>
<p><%= @lesson.content %></p>

<%= link_to t('.button_back'), student_course_path(@course) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('.login'), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('.signup'), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t('.forgot_password'), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>